### ISSUE TITLE
upgrade to 3.1.0 causes migration error

### ISSUE THREAD

**Issue by sleithart** [craftcms/commerce-stripe#232]
### Description

I'm upgrading a client site from Craft 3 to Craft 4. As part of that process, I've also upgraded Craft Commerce and the various plugins, including commerce-stripe from 2.4.4 to 3.1.0. This involves upgrading from the Stripe Charge gateway to Payment Intents gateway.

When I import my production database and run the migrations, one of the craft-commerce migrations tries to delete the charge gateway, but can't because I have existing subscriptions associated with that gateway. The specific error is below.

```
Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (db.craft_commerce_subscriptions, CONSTRAINT craft_fk_nkrpvlpaaadibceuvlfkqmqbpjltlkrnrtvx FOREIGN KEY (gatewayId) REFERENCES craft_commerce_gateways (id))
The SQL being executed was: DELETE FROM craft_commerce_gateways WHERE id='2'

Migration: craft\commerce\stripe\migrations\m220406_160425_remove_charge_gateway_references

Output:

> update in {{%commerce_orders}} ... done (time: 0.001s)
> update in {{%commerce_transactions}} ... done (time: 0.001s)
> delete from {{%commerce_paymentsources}} ... done (time: 0.001s)
> delete from {{%commerce_gateways}} ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (db.craft_commerce_subscriptions, CONSTRAINT craft_fk_nkrpvlpaaadibceuvlfkqmqbpjltlkrnrtvx FOREIGN KEY (gatewayId) REFERENCES craft_commerce_gateways (id))
The SQL being executed was: DELETE FROM craft_commerce_gateways WHERE id='2' (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM cr...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('DELETE FROM cr...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(299): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/commerce-stripe/src/migrations/m220406_160425_remove_charge_gateway_references.php(34): yii\db\Migration->delete('{{%commerce_gat...', Array)
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): craft\commerce\stripe\migrations\m220406_160425_remove_charge_gateway_references->safeUp()
#5 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(craft\commerce\stripe\migrations\m220406_160425_remove_charge_gateway_references))
#7 /var/www/html/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#8 /var/www/html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations(Array)
#9 /var/www/html/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(302): yii\base\Module->runAction('updater/migrate', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(714): craft\web\Application->runAction('updater/migrate')
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(239): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
#19 {main}
```

### Steps to reproduce

1. Go through Craft 4 upgrade process
2. Import db from production
3. Go to Craft admin site and run the "Finish up" tasks

### Additional info

- Craft CMS version: 4.4.5
- Stripe for Craft Commerce version: 3.1.0
- PHP version: 8.0.2
- Database driver & version: mysql/mariadb
- Plugins & versions:

**Comment by pdaleramirez** [comment]
@sleithart Stripe Charge has been deprecated. To fix the issue, you need to unsubscribe or remove any existing subscription that uses Stripe charge, then rerun the migration.

**Comment by lukeholder** [comment]
Before you upgrade from 2.x to 3.x you should have switched to the payment intent gateway for that gateway ID since the old gateway type was deprecated in 2.0 (removed in 3.0)
