### ISSUE TITLE
Your Card Was Decline Error - 3D Secure

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce-stripe#75]
I could be misunderstanding how to catch this error, but I think it's an issue in the way either commerce-stripe (or commerce) handles the path defined below. Should note that 3D secure w/ successful card works and 3D secure "fail authentication" also works as expected, just not "complete authentication" where 3D secure fails intentionally. Let me know if I can give you any more details to help.

Replication steps:
1. Attempt to process payment with card 4000008400001629 (3D Secure Required Payment fails)
2. Click "complete authentication" on the "3D Secure Test Payment Page"
3. Was redirected to: local.dev/index.php?commerceTransactionHash=e51bcaefe6cd35995a9b4bbc5095dd4c&p=actions%2Fcommerce%2Fpayments%2Fcomplete-payment&payment_intent=pi_1FBkVk2v7dE4TgLwmcXVtE9i&payment_intent_client_secret=pi_1FBkVk2v7dE4TgLwmcXVtE9i_secret_KlPHCihTAWezVvTXF6nCeB8YU&source_type=card
4. With the error `Stripe\Error\Card Your card was declined.`

Versions:
```
        "craftcms/cms": "3.2.10",
        "craftcms/commerce": "2.1.12.1",
        "craftcms/commerce-stripe": "2.1.1",
```

Stack Trace:
```
Stripe\Error\Card: Your card was declined. in /home/vagrant/code/vendor/stripe/stripe-php/lib/ApiRequestor.php:214 from API request 'req_sUW6QThsm7ahLC'
Stack trace:
#0 /home/vagrant/code/vendor/stripe/stripe-php/lib/ApiRequestor.php(173): Stripe\ApiRequestor::_specificAPIError('{\n  "error": {\n...', 402, Object(Stripe\Util\CaseInsensitiveArray), Array, Array)
#1 /home/vagrant/code/vendor/stripe/stripe-php/lib/ApiRequestor.php(473): Stripe\ApiRequestor->handleErrorResponse('{\n  "error": {\n...', 402, Object(Stripe\Util\CaseInsensitiveArray), Array)
#2 /home/vagrant/code/vendor/stripe/stripe-php/lib/ApiRequestor.php(126): Stripe\ApiRequestor->_interpretResponse('{\n  "error": {\n...', 402, Object(Stripe\Util\CaseInsensitiveArray))
#3 /home/vagrant/code/vendor/stripe/stripe-php/lib/ApiOperations/Request.php(57): Stripe\ApiRequestor->request('post', '/v1/payment_int...', Array, Array)
#4 /home/vagrant/code/vendor/stripe/stripe-php/lib/ApiOperations/Request.php(39): Stripe\ApiResource::_staticRequest('post', '/v1/payment_int...', Array, Object(Stripe\Util\RequestOptions))
#5 /home/vagrant/code/vendor/stripe/stripe-php/lib/PaymentIntent.php(102): Stripe\ApiResource->_request('post', '/v1/payment_int...', Array, NULL)
#6 /home/vagrant/code/vendor/craftcms/commerce-stripe/src/gateways/PaymentIntents.php(397): Stripe\PaymentIntent->confirm(Array)
#7 /home/vagrant/code/vendor/craftcms/commerce-stripe/src/gateways/PaymentIntents.php(175): craft\commerce\stripe\gateways\PaymentIntents->_confirmPaymentIntent(Object(Stripe\PaymentIntent), Object(craft\commerce\models\Transaction))
#8 /home/vagrant/code/vendor/craftcms/commerce/src/services/Payments.php(339): craft\commerce\stripe\gateways\PaymentIntents->completePurchase(Object(craft\commerce\models\Transaction))
#9 /home/vagrant/code/vendor/craftcms/commerce/src/controllers/PaymentsController.php(404): craft\commerce\services\Payments->completePayment(Object(craft\commerce\models\Transaction), '')
#10 [internal function]: craft\commerce\controllers\PaymentsController->actionCompletePayment()
#11 /home/vagrant/code/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/vagrant/code/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /home/vagrant/code/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('complete-paymen...', Array)
#14 /home/vagrant/code/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('complete-paymen...', Array)
#15 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('commerce/paymen...', Array)
#16 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('commerce/paymen...', Array)
#17 /home/vagrant/code/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /home/vagrant/code/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/vagrant/code/public/index.php(24): yii\base\Application->run()
#20 {main}
```

**Comment by nfourtythree** [comment]
Hey @dhahn 

I have managed to replicate this issue. Have pushed up a commit that will hopefully deal with this (cd2b08a71ee545483fb05e0a4d9369862dfa47e6).

Will look to see if we can get it released

**Comment by dhahn** [comment]
Awesome! I will check this out later today!

**Comment by dhahn** [comment]
That commit fixes the issue for on my end. 🙌
