### ISSUE TITLE
Undefined index issue when clicking on subscription

### ISSUE THREAD

**Issue by johnwbaxter** [craftcms/commerce-stripe#81]
When I click on a subscription in the admin area i.e example.com/admin/commerce/subscriptions/124447 i get "Undefined index: created"

```
644b0550fa06266a7474ae351e75a85][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: created in /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/commerce-stripe/src/base/SubscriptionGateway.php:203
Stack trace:
#0 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/srv/users/fand...', 203)
#1 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/commerce-stripe/src/base/SubscriptionGateway.php(203): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/srv/users/fand...', 203, Array)
#2 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/commerce/src/elements/Subscription.php(333): craft\commerce\stripe\base\SubscriptionGateway->getSubscriptionPayments(Object(craft\commerce\elements\Subscription))
#3 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Extension/CoreExtension.php(1687): craft\commerce\elements\Subscription->getAllPayments()
#4 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\elements\Subscription), 'getAllPayments', Array, 'method', false, false)
#5 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/82/82e42f0ca20792ef88f4fabe51cd31a09d099502f75d55616afac5231e6c5e9f.php(367): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\elements\Subscription), 'getAllPayments', Array, 'method')
#6 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(184): __TwigTemplate_2c58361150355a6b293e641335396e71e3c8215d79f6891615d5f011aa9e8118->block_content(Array, Array)
#7 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/30/305d8957d2898273ef538934120c22fc5b18eb2b9894e8ef5eae13c3f07c6675.php(660): Twig\Template->displayBlock('content', Array, Array)
#8 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(184): __TwigTemplate_b67d6bf5df714f9dd5571489e7b90e7e55aa8c287915fcf8d1d2f6cabad873c1->block_main(Array, Array)
#9 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/30/305d8957d2898273ef538934120c22fc5b18eb2b9894e8ef5eae13c3f07c6675.php(545): Twig\Template->displayBlock('main', Array, Array)
#10 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(184): __TwigTemplate_b67d6bf5df714f9dd5571489e7b90e7e55aa8c287915fcf8d1d2f6cabad873c1->block_body(Array, Array)
#11 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/c3/c395e3c67c10356a7933246ac64ff70aacfbcfd60f3a5bd92ddac272162f003b.php(72): Twig\Template->displayBlock('body', Array, Array)
#12 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(382): __TwigTemplate_7d499fea5497fae9f2fe72a72782b036cd83ffdf468e9271ec59dd64919eee4a->doDisplay(Array, Array)
#13 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#15 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#16 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/eb/ebba83483e2a66c4260c612f2d34e5ce14d1f216a33d93f5790c2e80b417bf41.php(52): craft\web\twig\Template->display(Array, Array)
#17 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(382): __TwigTemplate_0365e790a3352223226b4a919083f0d4b36a4cf0b24d878d002c748739841cb1->doDisplay(Array, Array)
#18 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#20 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#21 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/30/305d8957d2898273ef538934120c22fc5b18eb2b9894e8ef5eae13c3f07c6675.php(107): craft\web\twig\Template->display(Array, Array)
#22 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(382): __TwigTemplate_b67d6bf5df714f9dd5571489e7b90e7e55aa8c287915fcf8d1d2f6cabad873c1->doDisplay(Array, Array)
#23 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#25 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#26 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/df/dfae3a175dd395a864db982bfe529c6c62ae4117d246b9c3385fe073c08f4a35.php(42): craft\web\twig\Template->display(Array, Array)
#27 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(382): __TwigTemplate_f20f0c1af8fc35925781fe4646ed54b02a11c068a8186e404d3e01152733d809->doDisplay(Array, Array)
#28 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#30 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#31 /srv/users/xxxxxx/apps/xxxxxx/storage/runtime/compiled_templates/82/82e42f0ca20792ef88f4fabe51cd31a09d099502f75d55616afac5231e6c5e9f.php(71): craft\web\twig\Template->display(Array, Array)
#32 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(382): __TwigTemplate_2c58361150355a6b293e641335396e71e3c8215d79f6891615d5f011aa9e8118->doDisplay(Array, Array)
#33 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#34 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#35 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#36 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Template.php(367): craft\web\twig\Template->display(Array)
#37 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#38 /srv/users/xxxxxx/apps/xxxxxx/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#39 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('commerce/subscr...', Array)
#40 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('commerce/subscr...', Array)
#41 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('commerce/subscr...', Array)
#42 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/commerce/src/controllers/SubscriptionsController.php(66): craft\web\Controller->renderTemplate('commerce/subscr...', Array)
#43 [internal function]: craft\commerce\controllers\SubscriptionsController->actionEdit(124447, NULL)
#44 /srv/users/xxxxxx/apps/xxxxxx/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#45 /srv/users/xxxxxx/apps/xxxxxx/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#46 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit', Array)
#47 /srv/users/xxxxxx/apps/xxxxxx/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit', Array)
#48 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerce/subscr...', Array)
#49 /srv/users/xxxxxx/apps/xxxxxx/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('commerce/subscr...', Array)
#50 /srv/users/xxxxxx/apps/xxxxxx/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#51 /srv/users/xxxxxx/apps/xxxxxx/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#52 /srv/users/xxxxxx/apps/xxxxxx/public/index.php(21): yii\base\Application->run()

```

**Comment by johnwbaxter** [comment]
hol up, i'm well behind on versions here but craft says it's fully up-to-date. Damn it. Sorry!!
